CREATE TABLE `COMMISSION_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_COMMISSION` bigint(20) DEFAULT NULL,
  `ID_ITEM` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ID_COMMISSION` (`ID_COMMISSION`),
  KEY `FK_ID_ITEM` (`ID_ITEM`),
  CONSTRAINT `FK_ID_COMMISSION` FOREIGN KEY (`ID_COMMISSION`) REFERENCES `COMMISSION` (`ID`),
  CONSTRAINT `FK_ID_ITEM` FOREIGN KEY (`ID_ITEM`) REFERENCES `ITEM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
