CREATE TABLE `ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTENT` longtext COLLATE utf8_bin,
  `ITEM_NAME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PRICE` float DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;